[package]
name = "graphannis"
version = "0.11.1" #:version
authors = ["Thomas Krause <thomaskrause@posteo.de>"]

license = "Apache-2.0"
description = "This is a prototype for a new backend implementation of the ANNIS linguistic search and visualization system."
repository= "https://github.com/corpus-tools/graphANNIS"
readme = "crate-info.md"
autobins=true
build = "build.rs"

[lib]
crate-type = ["rlib", "staticlib","cdylib"]

[build-dependencies]
lalrpop = "0.16"

[dependencies]
regex = "1.0"
regex-syntax = "0.6"
serde = {version="1.0", features=["rc"]}
serde_derive = "1.0"
bincode = "1.0"
rand = "0.5"
csv = "1.0"
multimap = "0.4"
log = "0.4"
lazy_static = "1.1"
strum = "0.11"
strum_macros = "0.11"
num = "0.2"
linked-hash-map = "0.5"
tempdir = "0.3"
itertools = "0.7"
rustc-hash = "1.0"
rayon = "1.0"
sys-info = "0.5"
fs2 = "0.4"
lalrpop-util = "0.16"
error-chain = "0.12"
boolean_expression = "0.3"

graphannis-malloc_size_of = "1.0"
graphannis-malloc_size_of_derive = "1.0"

rustyline = {version="1.0", optional=true }
simplelog = {version="0.5", optional=true}
clap = {version="2", optional=true}
criterion = {version="0.2", optional=true}
prettytable-rs = {version="0.8", optional=true}

libc = {version="0.2", optional=true}

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docs_rs_workaround"]

[target.'cfg(windows)'.dependencies]
kernel32-sys = { version = "0.2.2" }

[dev-dependencies]
simplelog = "0.5"

[features]
cli = ["rustyline", "simplelog", "clap", "prettytable-rs"]
c-api = ["libc", "simplelog"]

[profile.release]
incremental = true

[[bench]]
name = "graphannis"
harness = false

[[bin]]
name="annis"
required-features=["cli"]

[[bin]]
name="bench_annisqueries"
required-features=["criterion", "simplelog", "clap"]
