[package]
name = "graphannis"
version = "0.26.0-dev"
authors = ["Thomas Krause <thomaskrause@posteo.de>"]

license = "Apache-2.0"
description = "This is a new backend implementation of the ANNIS linguistic search and visualization system."
repository= "https://github.com/korpling/graphANNIS"
readme = "crate-info.md"
autobins=true
build = "build.rs"
edition = "2018"

[lib]
crate-type = ["lib", "staticlib","cdylib"]

[build-dependencies]
lalrpop = "0.17"
csv = "1"
regex = "1"
file_diff = "1"

[dependencies]
regex = "1"
regex-syntax = "0.6"
serde = {version="1.0", features=["rc"]}
serde_derive = "1.0"
bincode = "1.2"
rand = {version = "0.7", features=["small_rng"]}
csv = "1"
shardio = "0.6"
sstable = "0.6"
failure = "0.1"
multimap = {version = "0.8", default-features=false}
log = "0.4"
lazy_static = "1.4"
strum = "0.17"
strum_macros = "0.17"
num-traits = "0.2"
linked-hash-map = "0.5"
tempfile = "3.1"
itertools = "0.8"
rustc-hash = "1.0"
rayon = {version="1.3",  default-features=false}
sys-info = "0.5"
fs2 = "0.4"
lalrpop-util = "0.17"
boolean_expression = "0.3"
percent-encoding = "1.0"
rocksdb = {version ="0.13.0", default-features = false}
libc = {version="0.2"}

graphannis-malloc_size_of = "1.0"
graphannis-malloc_size_of_derive = "2.0"

rustyline = {version="6.0", optional=true }
rustyline-derive = {version="0.3", optional=true }
simplelog = {version="0.7", optional=true}
clap = {version="2", optional=true, default-features=false}
criterion = {version="0.3", optional=true, default-features=false}
prettytable-rs = {version="0.8", optional=true, default-features=false}


[target.'cfg(windows)'.dependencies]
kernel32-sys = { version = "0.2.2" }

[dev-dependencies]
criterion = "0.3"
env_logger = "0.6"

[features]
cli = ["rustyline", "rustyline-derive", "simplelog", "clap", "prettytable-rs"]
c-api = ["simplelog"]

[profile.release]
incremental = true

[[bench]]
name = "graphannis"
harness = false

[[bin]]
name="annis"
required-features=["cli"]

[[bin]]
name="bench_annisqueries"
required-features=["criterion", "simplelog", "clap"]
