[package]
name = "malloc_size_of"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MIT/Apache-2.0"
publish = false
description = "This is a copy from Servo with some non-used data structures removed and some added."

[lib]
path = "lib.rs"

[dependencies]
void = "1.0.2"
