[package]
name = "graphannis-cli"
version = "0.1.0"
authors = ["Thomas Krause <thomaskrause@posteo.de>"]

workspace = ".."

[dependencies]
graphannis = {path = "../graphannis"}
rustyline = "1.0"
log = "0.3"
simplelog = "0.4"
clap = "2"