[package]
name = "graphannis-cli"
version = "0.1.0"
authors = ["Thomas Krause <thomaskrause@posteo.de>"]

license = "Apache-2.0"
description = "This is command line interface for a prototype of a new backend implementation of the ANNIS linguistic search and visualization system."
repository= "https://github.com/thomaskrause/graphANNIS"


workspace = ".."

[dependencies]
graphannis = {path = "../graphannis"}
rustyline = "1.0"
log = "0.4"
simplelog = "0.5"
clap = "2"
bencher = "0.1"
lazy_static = "1.0"