[package]
name = "graphannis-base"
version = "0.1.0"
authors = ["Thomas Krause <thomaskrause@posteo.de>"]

[dependencies]
regex = "0.2"

tempdir = "0.3"

serde = "1.0"
serde_derive = "1.0"
bincode = "0.8"