[package]
name = "graphannis-core"
version = "0.26.0"
authors = ["Thomas Krause <thomaskrause@posteo.de>"]

license = "Apache-2.0"
description = "This crate supports graph representation and generic query-functionality."
repository= "https://github.com/korpling/graphANNIS"
readme = "crate-info.md"
edition = "2018"

[lib]

[dependencies]
graphannis-malloc_size_of = "1.0"
graphannis-malloc_size_of_derive = "2.0"
num-traits = "0.2"
serde = {version="1.0", features=["rc"]}
serde_derive = "1.0"
strum = "0.18"
strum_macros = "0.18"
anyhow="1"
sstable = "0.8.1"
bincode = "1.2"
log = "0.4"
tempfile = "3.1"
rustc-hash = "1.0"

[dev-dependencies]
fake = "2.2"