version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
platform:
   - x64
   #- x86

clone_depth: 50

environment:
  matrix:
    - subset: sse
    - subset: avx

build_script:
- cmd: >-
    CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%

    ctest -VV -S C:\projects\vc\test.cmake
