[bind]
host = "localhost"
port = 5711

[database]
disk_based = false
graphannis = "data/"
sqlite = "service.sqlite"

[auth.token_verification]
secret = "not-a-random-secret"
type = "HS256"

[logging]
debug = false
