[bind]
port = 5711
host = "localhost"

[database]
graphannis = "data/"
sqlite = "service.sqlite"

[auth]
jwt_secret = ""
redirect_token_parameter = "auth_token"
expiration_minutes = 120

[logging]
debug = false

[users]