[bind]
host = "localhost"
port = 5711

[database]
disk_based = false
graphannis = "data/"
sqlite = "service.sqlite"

[auth]
token_verification = {HS256 = "not-a-random-secret"}

[logging]
debug = false
