[bind]
port = 5711
host = "localhost"

[database]
graphannis = "data/"
sqlite = "service.sqlite"
disk_based = false

[auth]
token_verification = {HS256 = "not-a-random-secret"}
expiration_minutes = 120

[logging]
debug = false

[users]