[package]
name = "graphannis-webservice"
version = "0.27.0"
authors = ["Thomas Krause <thomaskrause@posteo.de>"]
license = "Apache-2.0"
description = "This is a web service to the new backend implementation of the ANNIS linguistic search and visualization system."
repository = "https://github.com/korpling/graphANNIS"
readme = "crate-info.md"
edition = "2018"

[dependencies]
graphannis= {path = "../graphannis/", version= "^0.27"}
simplelog = "0.7"
clap = "2"
anyhow = "1"
log = "0.4"
actix-web = "2"
actix-rt = "1"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
config = "0.10"
bcrypt = "0.8"